version: '3.8'
services:
  app:
    build: .
    container_name: clean-arch-app
    ports:
      - '5001:5000' # Change 5001 to any free port
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: clean-arch-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
volumes:
  mongo_data:
